### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by fagundes** [yajra/pdo-via-oci8#109]
When trying to use the lib in php 8.1 I'm getting the following error:

```bash 

Trace:
#0 .../vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php(690): get_mangled_object_vars(Array)

...

Exception: get_mangled_object_vars(): Argument #1 ($object) must be of type object, array given

```

### Summary of problem or feature request

Argument must be object type in `get_mangled_object_vars`.

Possible fix is cast to object, like so:

```php
 $mangledObj = get_mangled_object_vars((object)$row);
```

### System details

- Operating System GNU/Linux
- PHP Version 8.1
- PDO-VIA-OCI8 3.2.3

**Comment by yajra** [comment]
Thanks for reporting, fixed on v3.2.4
