### ISSUE TITLE
getAttribute returning empty array instead of null in PHP v8.1.16

### ISSUE THREAD

**Issue by PauloGraca** [yajra/pdo-via-oci8#123]
https://github.com/yajra/pdo-via-oci8/blob/2666f4c15d3472338874d1df567757d5854b800e/src/Pdo/Oci8.php#L492

When PDO attribute is not set the method `getAttribute()` returns empty array `[]`  while it should return `null`.

This will be an issue downstream when methods will expect a string or null resulting in `ERROR: Array to string conversion`.

Example of usage for this attribute: Laravel Queue https://github.com/laravel/framework/blob/38f022d01fd85caf88c11cec52dade7ccccccfdf/src/Illuminate/Queue/DatabaseQueue.php#L259:L261 

Thank you in advance for looking into this!

**Comment by yajra** [comment]
Thanks for reporting. I agree that this method should return `null` based on the description and [php.net](https://www.php.net/manual/en/pdo.getattribute.php):

> A successful call returns the value of the requested PDO attribute. An unsuccessful call returns null.

**Comment by PauloGraca** [comment]
Thanks for the quick fix! :) 👍
