### ISSUE TITLE
oci_connect(): OCI_SUCCESS_WITH_INFO: ORA-28002: the password will expire within 97 days

### ISSUE THREAD

**Issue by supuna97** [yajra/pdo-via-oci8#135]
### Summary of problem or feature request

I tried to get data from query. But this warning causes the application to crash. But this works fine in pdo-via-oci8 v2.0. The error is giving the version from  pdo-via-oci8 v3.0.

### Code snippet of problem

```php
try {
    $pdo = DB::connection('core')->getPdo();
} catch (\Throwable $e) {
    dd($e);
}
```

### System details

- Ubuntu 22.04
- PHP 8.1
- PDO-VIA-OCI8 3.0

**Comment by yajra** [comment]
On v2, we used to suppress the error. Do you think we should revert it? Please feel free to submit a PR.

v3
https://github.com/yajra/pdo-via-oci8/blob/3.0/src/Pdo/Oci8.php#L142

v2
https://github.com/yajra/pdo-via-oci8/blob/2.0/src/Pdo/Oci8.php#L480

**Comment by supuna97** [comment]
Fixed. Refer #136
