### ISSUE TITLE
Update to v1.0.0 not connect in L4.2

### ISSUE THREAD

**Issue by joseate** [yajra/pdo-via-oci8#22]
I updated from v0.15.0 to v1.0.0 and cann't connect to DB, change de namespace yajra to Yajra in /OCI8/Connectors/OracleConnector.php to make it run.

**Comment by yajra** [comment]
Yes, Laravel-OCI8 for L4.2 uses version ~0.15. What version on OCI8 do you use? Will try to update that branch to use v1.0.0 by default. Thanks!

**Comment by yajra** [comment]
Oh memory gap! L4.2 & 5.0 uses OCI8 `~2.4`. Will update the package to use v1.0. Thanks!

**Comment by yajra** [comment]
Laravel-OCI8 v2.4.6 released and it now uses pdo-via-oci8: ~1.0. Kindly check test and verify. Thanks!
