### ISSUE TITLE
fetchAll error while fetch return not array

### ISSUE THREAD

**Issue by dkochnov** [yajra/pdo-via-oci8#27]
function fetchAll()  if  $this->fetch() return not array (as example - FETCH_COLUMN)

		$this->_results = array();
		while ($row = $this->fetch())
		{
			if (is_resource(reset($row))) {

then line with reset($row) throw Database Exception – yii\db\Exception
reset() expects parameter 1 to be array, string given

**Comment by yajra** [comment]
@dkochnov, would you be able to submit a PR to fix this? I am using this package via Laravel and I think you are using YII. It would be better if the fix would come from you? Thanks a lot!

**Comment by dkochnov** [comment]
of course, thank you
https://github.com/yajra/pdo-via-oci8/pull/28

**Comment by yajra** [comment]
@dkochnov thanks a lot for the PR. Merged and released on v1.0.3 👍
