### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by paragshar** [yajra/pdo-via-oci8#32]
I have to use pdo-via-oci with laraval/Asgard CMS application. I was wondering how to configure the pdo-via-oci8 driver. What are the steps to be followed after installing it via composer? Where do I specify the Oracle credentials? How does the PDO driver get access to these credentials?

**Comment by yajra** [comment]
@paragshar you need to use [laravel-oci8](https://github.com/yajra/laravel-oci8) and `pdo-via-oci8` will be installed with it.
