### ISSUE TITLE
bindParam using wrong number when using ? in statement

### ISSUE THREAD

**Issue by istaveren** [yajra/pdo-via-oci8#64]
### bindParam using wrong param number when using ?

When you try to bind params with ? the first one should be 1 not 0.

### Code snippet of problem

```php
$stmt = $this->con->prepare('INSERT INTO person (name) VALUES (?)');
$var = 'Joop';
$stmt->bindParam(1, $var, PDO::PARAM_STR);
```

**Comment by yajra** [comment]
I didn't know bindParams work like that? 😄 Will check the PR again once the conflict was resolved. 

BTW, if possible, can you please create another PR for this issue. #63 is getting bigger and might be hard to rollback just in case there are some breaking changes that we might missed. Thanks!

**Comment by yajra** [comment]
Upon further review, it appears that this syntax is not yet supported because we are mapping `bindParam` to `oci_bind_by_name` which requires a colon-prefixed bind variable placeholder.

**Comment by istaveren** [comment]
That will also work. 
But if it is an int it should start with 1.
