### ISSUE TITLE
Declaration of Yajra\Pdo\Oci8::query($statement, $fetchMode = null, $modeArg = null, $ctorArgs = null) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

### ISSUE THREAD

**Issue by hpwahyao** [yajra/pdo-via-oci8#86]
### Summary of problem or feature request

Declaration of Yajra\Pdo\Oci8::query($statement, $fetchMode = null, $modeArg = null, $ctorArgs = null) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

- macOS Catalina
- PHP 8
- PDO-VIA-OCI8 Version: 1.x

**Comment by sciracioglu** [comment]
+1

**Comment by mu1f407** [comment]
Occurs only on PHP 8. After downgrade to 7.4.15 this error disappear.

**Comment by mu1f407** [comment]
Signature of PDO::query method has changed in 8.0:
https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.pdo

I will create PR when I have enought time.

**Comment by yajra** [comment]
PHP8 is currently supported on v3 / Laravel 8. See https://github.com/yajra/pdo-via-oci8/pull/83 for ref. PR is welcome. Thanks!

**Comment by yserrata** [comment]
yajra/laravel-pdo-via-oci8 
requires
php: ^8.0
but yajra/laravel-oci8 
requires
php: ^7.3
ext-oci8: >=2.0.0 doesn't have sense if the Driver support 7.3^ & 8.* but the libraries does not. i have a issue with PHP 7.3 on this.

**Comment by whoilo** [comment]
I have the same issue on php 7.4.22, dont know why.
Downgrade from 8.4.1 to 8.2.2 helps

**Comment by williemwewa** [comment]
No other resolution to this issue? Am using oracle 19 and php 8

**Comment by yajra** [comment]
When using PHP 8 & 8.1, use v3. Anything below 8, use v2 of the package.
